import type { Trip, TripItem } from "../domain/types";

/**
 * A realistic trip so every screen opens with something to look at, and so the
 * checks have something to catch. Several problems are deliberate: an expiring
 * passport, a 45-minute international layover, a museum booked too far from the
 * previous stop, and two things booked at the same time.
 */
export const SEED_TRIP: Trip = {
  id: "trip-japan-autumn",
  name: "Japan, autumn",
  homeCountry: "IN",
  destinationCountries: ["JP"],
  startDate: "2026-10-14",
  endDate: "2026-10-22",
  budgetTarget: { amount: 150000, currency: "INR" },
  travelers: [
    {
      id: "traveler-sehej",
      name: "Sehej Sharma",
      passportCountry: "IN",
      passportExpiry: "2026-10-18",
      insuranceFrom: "2026-10-14",
      insuranceTo: "2026-10-20",
    },
    {
      id: "traveler-aanya",
      name: "Aanya Rao",
      passportCountry: "IN",
      passportExpiry: "2029-03-11",
    },
  ],
};

interface SeedItem
  extends Omit<TripItem, "tripId" | "createdAt" | "confidence" | "extractionMethod"> {
  confidence?: number;
}

const SEED_ENTRIES: SeedItem[] = [
  {
    id: "item-flight-out",
    title: "AI142 DEL → HND",
    category: "booking",
    bookingKind: "flight",
    source: "gmail",
    sourceRef: "Air India booking confirmation",
    place: {
      name: "Indira Gandhi International",
      city: "Delhi",
      countryCode: "IN",
      point: { lat: 28.5562, lng: 77.1 },
      airport: "DEL",
    },
    arrivalPlace: {
      name: "Tokyo Haneda",
      city: "Tokyo",
      countryCode: "JP",
      point: { lat: 35.5494, lng: 139.7798 },
      airport: "HND",
    },
    startsAt: "2026-10-14T19:55:00+05:30",
    endsAt: "2026-10-15T07:25:00+09:00",
    cost: { amount: 52400, currency: "INR" },
    costStatus: "actual",
    confirmationCode: "X4RT9K",
    travelerName: "Sehej Sharma",
  },
  {
    id: "item-hotel",
    title: "Shinjuku Granbell Hotel",
    category: "booking",
    bookingKind: "lodging",
    source: "gmail",
    sourceRef: "Booking confirmation",
    place: {
      name: "Shinjuku Granbell Hotel",
      city: "Tokyo",
      countryCode: "JP",
      point: { lat: 35.6938, lng: 139.7036 },
    },
    startsAt: "2026-10-15T15:00:00+09:00",
    endsAt: "2026-10-22T11:00:00+09:00",
    cost: { amount: 168000, currency: "JPY" },
    costStatus: "actual",
    confirmationCode: "BK88213",
    travelerName: "S Sharma",
    refundableUntil: "2026-09-14T23:59:00+09:00",
  },
  {
    id: "item-teamlab",
    title: "teamLab Borderless",
    category: "activity",
    source: "reel",
    sourceRef: "instagram.com/reel/azabudai-lights",
    place: {
      name: "teamLab Borderless",
      city: "Tokyo",
      countryCode: "JP",
      point: { lat: 35.6605, lng: 139.7396 },
    },
    startsAt: "2026-10-16T13:00:00+09:00",
    endsAt: "2026-10-16T14:30:00+09:00",
    cost: { amount: 3800, currency: "JPY" },
    costStatus: "actual",
    confirmationCode: "TLB4402",
  },
  {
    id: "item-ghibli",
    title: "Ghibli Museum",
    category: "activity",
    source: "screenshot",
    sourceRef: "Ticket screenshot",
    place: {
      name: "Ghibli Museum",
      city: "Mitaka",
      countryCode: "JP",
      point: { lat: 35.6962, lng: 139.5704 },
    },
    startsAt: "2026-10-16T15:00:00+09:00",
    endsAt: "2026-10-16T17:00:00+09:00",
    cost: { amount: 1000, currency: "JPY" },
    costStatus: "actual",
  },
  {
    id: "item-shibuya-sky",
    title: "Shibuya Sky at sunset",
    category: "activity",
    source: "tiktok",
    place: {
      name: "Shibuya Sky",
      city: "Tokyo",
      countryCode: "JP",
      point: { lat: 35.658, lng: 139.7016 },
    },
    startsAt: "2026-10-17T17:30:00+09:00",
    endsAt: "2026-10-17T18:30:00+09:00",
    cost: { amount: 2600, currency: "JPY" },
    costStatus: "estimated",
  },
  {
    id: "item-omoide",
    title: "Dinner at Omoide Yokocho",
    category: "place",
    source: "reel",
    place: {
      name: "Omoide Yokocho",
      city: "Tokyo",
      countryCode: "JP",
      point: { lat: 35.6938, lng: 139.7 },
    },
    startsAt: "2026-10-17T19:00:00+09:00",
    endsAt: "2026-10-17T21:00:00+09:00",
  },
  {
    id: "item-sensoji",
    title: "Senso-ji early morning",
    category: "place",
    source: "youtube",
    place: {
      name: "Senso-ji",
      city: "Tokyo",
      countryCode: "JP",
      point: { lat: 35.7148, lng: 139.7967 },
    },
    startsAt: "2026-10-18T09:00:00+09:00",
    endsAt: "2026-10-18T10:30:00+09:00",
  },
  {
    id: "item-tsukiji",
    title: "Tsukiji Outer Market",
    category: "place",
    source: "reel",
    place: {
      name: "Tsukiji Outer Market",
      city: "Tokyo",
      countryCode: "JP",
      point: { lat: 35.6654, lng: 139.7707 },
    },
    startsAt: "2026-10-18T11:15:00+09:00",
    endsAt: "2026-10-18T12:30:00+09:00",
  },
  {
    id: "item-cooking",
    title: "Ramen cooking class",
    category: "activity",
    source: "gmail",
    startsAt: "2026-10-20T11:00:00+09:00",
    endsAt: "2026-10-20T14:00:00+09:00",
    cost: { amount: 8500, currency: "JPY" },
    costStatus: "actual",
    confirmationCode: "CKC9911",
  },
  {
    id: "item-sumo",
    title: "Sumo tournament — Ryogoku",
    category: "activity",
    source: "screenshot",
    startsAt: "2026-10-20T13:00:00+09:00",
    endsAt: "2026-10-20T17:00:00+09:00",
    cost: { amount: 6200, currency: "JPY" },
    costStatus: "actual",
  },
  {
    id: "item-national-museum",
    title: "Tokyo National Museum",
    category: "activity",
    source: "youtube",
    place: {
      name: "Tokyo National Museum",
      city: "Tokyo",
      countryCode: "JP",
      point: { lat: 35.7188, lng: 139.7766 },
    },
    startsAt: "2026-10-19T10:00:00+09:00",
    endsAt: "2026-10-19T12:30:00+09:00",
    addedBy: "traveler-aanya",
  },
  {
    id: "item-flight-home-1",
    title: "TG683 HND → BKK",
    category: "booking",
    bookingKind: "flight",
    source: "gmail",
    place: {
      name: "Tokyo Haneda",
      city: "Tokyo",
      countryCode: "JP",
      point: { lat: 35.5494, lng: 139.7798 },
      airport: "HND",
    },
    arrivalPlace: {
      name: "Suvarnabhumi",
      city: "Bangkok",
      countryCode: "TH",
      point: { lat: 13.69, lng: 100.7501 },
      airport: "BKK",
    },
    startsAt: "2026-10-22T00:10:00+09:00",
    endsAt: "2026-10-22T04:50:00+07:00",
    cost: { amount: 31900, currency: "INR" },
    costStatus: "actual",
    confirmationCode: "TG55PL",
    travelerName: "Sehej Sharma",
  },
  {
    id: "item-flight-home-2",
    title: "TG315 BKK → DEL",
    category: "booking",
    bookingKind: "flight",
    source: "gmail",
    place: {
      name: "Suvarnabhumi",
      city: "Bangkok",
      countryCode: "TH",
      point: { lat: 13.69, lng: 100.7501 },
      airport: "BKK",
    },
    arrivalPlace: {
      name: "Indira Gandhi International",
      city: "Delhi",
      countryCode: "IN",
      point: { lat: 28.5562, lng: 77.1 },
      airport: "DEL",
    },
    startsAt: "2026-10-22T05:35:00+07:00",
    endsAt: "2026-10-22T08:25:00+05:30",
    costStatus: "actual",
    confirmationCode: "TG55PL",
    travelerName: "Sehej Sharma",
  },
  {
    id: "item-fushimi",
    title: "Fushimi Inari before sunrise",
    category: "place",
    source: "reel",
    sourceRef: "https://www.instagram.com/reel/C8kyoto2torii/",
    place: {
      name: "Fushimi Inari Taisha",
      city: "Kyoto",
      countryCode: "JP",
      point: { lat: 34.9671, lng: 135.7727 },
    },
    startsAt: "2026-10-21T07:00:00+09:00",
    endsAt: "2026-10-21T09:30:00+09:00",
    addedBy: "traveler-aanya",
  },
  {
    id: "item-arashiyama",
    title: "Arashiyama Bamboo Grove",
    category: "place",
    source: "tiktok",
    place: {
      name: "Arashiyama Bamboo Grove",
      city: "Kyoto",
      countryCode: "JP",
      point: { lat: 35.017, lng: 135.6714 },
    },
  },
  {
    id: "item-dotonbori",
    title: "Dotonbori street food crawl",
    category: "place",
    source: "youtube",
    place: {
      name: "Dotonbori",
      city: "Osaka",
      countryCode: "JP",
      point: { lat: 34.6687, lng: 135.5013 },
    },
  },
  {
    id: "item-kawaguchi",
    title: "Lake Kawaguchi for Fuji views",
    category: "place",
    source: "reel",
    place: {
      name: "Lake Kawaguchi",
      city: "Fujikawaguchiko",
      countryCode: "JP",
      point: { lat: 35.5171, lng: 138.752 },
    },
  },
  {
    id: "item-muji",
    title: "Muji stationery haul",
    category: "purchase",
    source: "reel",
    place: { name: "Tokyo", city: "Tokyo", countryCode: "JP" },
    cost: { amount: 8000, currency: "JPY" },
    costStatus: "estimated",
  },
  {
    id: "item-kitkat",
    title: "Regional Kit-Kat flavours for the office",
    category: "purchase",
    source: "screenshot",
    place: { name: "Tokyo", city: "Tokyo", countryCode: "JP" },
    cost: { amount: 3500, currency: "JPY" },
    costStatus: "estimated",
  },
  {
    id: "item-onsen",
    title: "Day trip to an onsen town",
    category: "activity",
    source: "youtube",
    place: { name: "Hakone", city: "Hakone", countryCode: "JP" },
  },
];

export const SEED_ITEMS: TripItem[] = SEED_ENTRIES.map((item) => ({
  ...item,
  tripId: SEED_TRIP.id,
  createdAt: "2026-09-01T09:00:00.000Z",
  confidence: item.confidence ?? 0.9,
  extractionMethod: "deterministic" as const,
}));
